version: "3"

services:
  mysql:
    image: mysql:latest
    networks:
      - db_network
    ports: # Exposes MySQL on the port set in the env file for development
      - "${MYSQL_EXPOSED_PORT}:3306"
    env_file:
      - .env
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  apache:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - db_network
    ports:
      - "8080:80"
    volumes:
      - "./public:/var/www/html"
      - "./src:/var/www/src"
      - "./composer.json:/var/www/composer.json"
# Uncomment if composer is installed locally and `composer install` is run before running Docker Compose
#      - "./vendor:/var/www/vendor"
#      - "./composer.json:/var/www/composer.json"
    depends_on:
      - mysql

networks:
  db_network:
    driver: bridge

volumes:
  mysql_data:
